version: "3.8"
services:
  bot:
    build: .
    command: "discord-embed-bot"
    volumes:
      # persist db across containers
      - ./chroma:/app/chroma
      # persist embedding models
      - ./sentence_transformers:/home/mambauser/web/sentence_transformers
    environment:
      - SENTENCE_TRANSFORMERS_HOME=./sentence_transformers
